name: nok
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  lottie: ^3.1.3
  provider: ^6.1.2
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/drinks/ 
    - assets/images/hamburgers/ 
    - assets/images/kfc/ 
    - assets/images/pizza/ 
    - assets/images/salads/ 
    - assets/animations/delivery.json
    - assets/animations/done.json